name: ANDROID BUILD

on  :
  workflow_dispatch

jobs:
  export-game:
    runs-on  : windows-latest
    permissions:
       write-all
    name :    Export Game
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        
      - name: setup java jdk
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: setup android sdk tools
        uses: android-actions/setup-android@v3.2.1

      - run : |
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debugs.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12
          move ./debugs.keystore  %USERPROFILE%\.android\
          mkdir -p                                            %USERPROFILE%\AppData\Roaming\Godot
          copy ${{ github.workspace }}/editor_settings-4.tres %USERPROFILE%\AppData\Roaming\Godot
      
      - name: export game
        id  : export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url      : https://downloads.tuxfamily.org/godotengine/4.3/dev5/Godot_v4.3-dev5_win64.exe.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/dev5/Godot_v4.3-dev5_export_templates.tpz
          relative_project_path: ./
          export_debug  : true
          verbose       : true
          archive_output: true
          
          
      - name: create release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag  : ${{ github.ref_name      }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*



          
          
          
